FROM ubuntu:latest
# FROM python:3.11.0-bullseye

USER root
# WORKDIR /workspace/movie-random-player

# RUN apt-get update && \
#     apt-get -y install --no-install-recommends \
#     python=3.11.0

# RUN pip install --upgrade \
#     pip && \
#     setuptools
# RUN pip install -r requirements.txt

# NOTE Docker コンテナ内のGUIアプリを起動してホスト側に表示する: https://zukucode.com/2019/07/docker-gui-show.html

#NOTE 一般ユーザーを追加: https://qiita.com/Spritaro/items/602118d946a4383bd2bb
# ARG USERNAME=user
# ARG GROUPNAME=user
# ARG UID=1000
# ARG GID=1000
# RUN groupadd -g ${GID} ${GROUPNAME} && \
#     useradd -m -s /bin/zsh -u ${UID} -g ${GID} ${USERNAME}

# USER ${USERNAME}
